In [14]:
import torch
import math

x = torch.empty(3,2,5)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[[3.0977e-18, 3.0850e-41, 3.0906e-18, 3.0850e-41, 1.1210e-43],
         [0.0000e+00, 8.9683e-44, 0.0000e+00, 3.1110e-18, 3.0850e-41]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 1.4013e-45, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 1.3593e-43, 0.0000e+00, 3.0907e-18],
         [3.0850e-41, 1.0354e+34, 4.5794e-41, 0.0000e+00, 0.0000e+00]]])


In [11]:
x.shape

torch.Size([3, 4, 5])

In [8]:
x.view(-1)

tensor([-2.2166e-21,  4.5793e-41,  8.2510e+32,  4.5794e-41,  2.0253e-20,
        -2.3787e+16, -2.2399e-21,  4.5793e-41,  8.2513e+32,  4.5794e-41,
        -2.6262e-14, -2.0518e+38])

In [24]:
a = torch.rand(3, 226, 226)

In [25]:
a

tensor([[[0.2234, 0.7869, 0.9796,  ..., 0.2343, 0.5907, 0.1655],
         [0.1559, 0.1984, 0.3483,  ..., 0.6157, 0.8972, 0.6121],
         [0.6201, 0.4529, 0.4326,  ..., 0.3733, 0.1174, 0.2893],
         ...,
         [0.7824, 0.7645, 0.4360,  ..., 0.3626, 0.7846, 0.4953],
         [0.5477, 0.5428, 0.7538,  ..., 0.6545, 0.8807, 0.8504],
         [0.7138, 0.8921, 0.2864,  ..., 0.0307, 0.7355, 0.4236]],

        [[0.5114, 0.2894, 0.1913,  ..., 0.3463, 0.9951, 0.8167],
         [0.9285, 0.9260, 0.5500,  ..., 0.5550, 0.2589, 0.4703],
         [0.8565, 0.3448, 0.6812,  ..., 0.2364, 0.8317, 0.0602],
         ...,
         [0.5660, 0.8739, 0.5996,  ..., 0.5643, 0.0650, 0.4774],
         [0.5163, 0.7655, 0.4932,  ..., 0.8769, 0.0770, 0.6079],
         [0.7999, 0.0682, 0.0573,  ..., 0.9397, 0.4793, 0.5197]],

        [[0.7335, 0.0672, 0.0119,  ..., 0.0681, 0.0674, 0.0701],
         [0.4934, 0.0812, 0.8383,  ..., 0.3021, 0.5048, 0.1266],
         [0.6371, 0.0683, 0.8878,  ..., 0.5561, 0.4834, 0.

In [30]:
a.view(-1)

tensor([0.2234, 0.7869, 0.9796,  ..., 0.3634, 0.5601, 0.9473])